server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    default: dev
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:ecommerce}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET:}
  expiration-ms: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
