server:
  port: 9102

spring:
  application:
    name: product-service
  profiles:
    default: dev
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:ecommerce}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ${JWT_SECRET:}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
